version: '3'

services:
  frontend:
    container_name: frontend-2
    build:
      context: ./client/
      dockerfile: Dockerfile
      args:
        - REACT_APP_SERVER_IP=${SERVER2_IP}
    ports:
      - "8080:80"
    restart: unless-stopped
    depends_on:
      - "real"
  real:
    container_name: real-backend-2
    build: 
      context: ./server/
      dockerfile: Dockerfile
      args:
        - MONGODB_URL=mongodb://realmodus:ritservices2022@192.168.0.101:27018,192.168.0.101:27019,192.168.0.101:27020/landtag-demo-test?replicaSet=rs
    ports:
      - "3333:3000"
    restart: unless-stopped
    depends_on:
      - "mongodb"
  test:
    container_name: test-backend-2
    build: 
      context: ./testserver/
      dockerfile: Dockerfile
      args:
        - MONGODB_URL=mongodb://testmodus:ritservices2022@192.168.0.101:27018,192.168.0.101:27019,192.168.0.101:27020/landtag-demo-test?replicaSet=rs
    ports:
      - "2929:2900"
    restart: unless-stopped
    depends_on:
      - "mongodb"
  
  loadbalancer:
    container_name: loadbalancer-2
    build:
      context: ./loadbalancer/
      dockerfile: Dockerfile
    ports:
      - 80:80
    depends_on:
      - "frontend"
  



  
    
    

    